Address failed Travis build by requiring vendor/autoload.php
In case this isn't required,
this might help with the Trave error:
Fatal error: Uncaught Error: Class 'WP_Mock' not found in